### ISSUE TITLE
Required attribute gets submitted without value

### ISSUE THREAD

**Issue by syed-haroon** [charliekassel/vuejs-datepicker#353]
Setting html required attribute on input fields doesn't work as expected and submits the form without have a input value.

Tried to get help from stackoverflow community, so far did not hear anything:
https://stackoverflow.com/q/47280866/1292050

**Comment by sv1979** [comment]
Have got the same issue, seems like has not been fixed. Form submits without value selected

**Comment by adamwright104** [comment]
When will this be fixed?

**Comment by isatrio** [comment]
For temporary solution you can refer my forking branch here https://github.com/isatrio/vuejs-datepicker. if you use Yarn use command below

yarn add git+https://github.com/isatrio/vuejs-datepicker.git#production

**Comment by adamwright104** [comment]
Hi i also fixed this by removing the read-only from the input after it renders. simply loop through and remove. would be cool if the plugin does this but not an issue for my project.

**Comment by charliekassel** [comment]
This should be resolved in v1 as the readonly attribute is removed.

**Comment by mik13ST** [comment]
I am using version 1.6.2 and the problem is back. The readonly attribute is still there.

The issue is not resolved.

**Comment by mik13ST** [comment]
I dug into it further and came up with a [reasonable solution](https://stackoverflow.com/a/69026389/5951116). I added it as an [answer ](https://stackoverflow.com/a/69033194/5951116) to the [mentioned StackOverflow question](https://stackoverflow.com/q/47280866/5951116).

I resolve this by allowing user input (which removes `readonly`) and then suppressing all user input manually.

But still, it's an issue of this library.
